#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Joy, JointState
import numpy as np

class Teleop:
	dt = 0.1

	def __init__(self, max_vel = 1):
		self.max_vel = max_vel
		rospy.init_node('teleop')
		self.q_pub = rospy.Publisher('/q', JointState, queue_size = 10)
		self.q = np.array([0, -1, 1.5, -0.5 - np.pi / 2, -np.pi / 2, 0])
		rate = rospy.Rate(5)
		self.velocity = np.zeros([6])
		self.goal = None
		rospy.Subscriber("joy", Joy, self.update, queue_size = 10)
		rate = rospy.Rate(1. / self.dt)
		while True:
			self.move()
			rate.sleep()

	def update(self, data):
		self.velocity[0] = self.max_vel * data.axes[0]
		self.velocity[1] = self.max_vel * data.axes[1]
		self.velocity[2] = self.max_vel * data.axes[3]
		self.velocity[3] = self.max_vel * data.axes[4]
		self.velocity[4] = self.max_vel * data.axes[6]
		self.velocity[5] = self.max_vel * data.axes[7]

	def move(self):
		self.q += self.dt * self.velocity
		msg = JointState()
		msg.position = self.q
		self.q_pub.publish(msg)

if __name__ == '__main__':
	Teleop()
